server:
  port: 8081
spring:
  application:
    name: SmartAttendanceManagement
# Database Credentials
  datasource:
    url: jdbc:mysql://localhost:3306/sam_db?createDatabaseIfNotExist=true
    username: root
    password: Ritik1234@
    driver-class-name: com.mysql.cj.jdbc.Driver
    generate-unique-name: false
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: default
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update